### ISSUE TITLE
 error message "Token is missing" appears when adding the Unifi Protect Controller

### ISSUE THREAD

**Issue by rtfm87** [seaside1/unifiprotect#1]
When I add the Unifi NVR, I get the error message "Token is missing". It has already been tested with multiple users, always the same behaviour. Protect Version is 1.13.7. Openhab Version is 2.5.10.

**Comment by seaside1** [comment]
Hi!
Sounds to me like you don't have the latest beta firmware which is needed if you run on Cloudkey gen2+.
You need beta firmware at least 2.0.18 for it to work.
See: https://community.ui.com/releases/UniFi-Cloud-Key-Firmware-2-0-22/2ba23601-5300-45fa-bd8d-a00ff13bd7b6 1
You need to be logged with your ubiquiti account in order to be able to see the post and download the beta firmware.

**Comment by rtfm87** [comment]
Thanks a lot, with the new firmware version the protect binding works great. Unfortunately the Unifi Network binding does not work anymore. Do you happen to know if there is a Unifi OS capable network binding available?

**Comment by seaside1** [comment]
I don't think so. I actually though it was working the same way as prior to UniFi OS.
I see that you have already posted in the thread here:
https://github.com/mgbowman/openhab-addons/issues/6
